-- Generated by tools.coefficient_lists.lean_example from the V24 producer.
import AlexandriaComplexity.CoefficientChecker
import AlexandriaComplexity.AffineProjection

namespace AlexandriaComplexity.CoefficientCertificateExample
open CoefficientChecker SpanReduction AffineProjection

def zero : List Bool := [false, false, false, false]
def original : List (List Bool) := [[true, true, false, false], [true, false, true, false], [false, true, true, false], [false, false, false, true]]
def source : List (List Bool) := [[true, true, false, false], [true, false, true, false], [false, true, true, false], [false, false, false, false]]
def target : List (List Bool) := [[true, true, false, false], [true, false, true, false]]
def lifts : List (List Bool) := [[true, true, false, false], [true, false, true, false]]
def forward : List (List Bool) := [[true, false, false, false], [false, true, false, false]]
def backward : List (List Bool) := [[true, false], [false, true], [true, true], [false, false]]

theorem projected_accepted : checkMutual zero xorV source target forward backward = true := by decide

theorem lifts_accepted : checkRows zero xorV original lifts forward = true := by decide

theorem corrupted_rejected :
    checkRows zero xorV source target [[false, false, false, false], [false, true, false, false]] = false := by decide

theorem projected_span (x : List Bool) :
    Span zero xorV source x ↔ Span zero xorV target x :=
  checkMutual_sound zero xorV source target forward backward projected_accepted x

theorem lifted_span : ∀ x, x ∈ lifts → Span zero xorV original x :=
  checkRows_sound zero xorV original lifts forward lifts_accepted

end AlexandriaComplexity.CoefficientCertificateExample
