import AlexandriaComplexity.SetResolution

namespace AlexandriaComplexity

/-!
Generated by `tools/generate_k4_lean_certificate.py` from the frozen
K4 JSON certificate. Do not edit this file by hand.

JSON SHA-256: `8aca9a752e342c53cda72d1e9446f94599322b400c907f464572c88bf1cb81ec`
Formula SHA-256: `d828e0ef6d411fb10816788896b3192aac95f48e09ab2de6d5987a6c5fbc881b`

This is one exact finite certificate, not an asymptotic lower bound or
a P-versus-NP result.
-/

def k4ResolutionCertificateJsonSHA256 : String :=
  "8aca9a752e342c53cda72d1e9446f94599322b400c907f464572c88bf1cb81ec"

def k4ResolutionFormulaSHA256 : String :=
  "d828e0ef6d411fb10816788896b3192aac95f48e09ab2de6d5987a6c5fbc881b"

private abbrev p (index : Nat) : Literal := positiveLiteral index
private abbrev n (index : Nat) : Literal := negativeLiteral index

theorem k4_set_resolution_certificate :
    SetResolutionDerivation k4OddTseitinCNF [] := by
  let c0 : Clause := [n 2, n 4, n 5]
  let c1 : Clause := [n 0, n 1, p 2]
  let c2 : Clause := [n 0, n 1, n 4, n 5]
  let c3 : Clause := [n 1, n 3, n 5]
  let c4 : Clause := [p 0, p 3, n 4]
  let c5 : Clause := [p 0, n 1, n 4, n 5]
  let c6 : Clause := [n 1, n 4, n 5]
  let c7 : Clause := [n 0, n 3, n 4]
  let c8 : Clause := [p 1, p 3, n 5]
  let c9 : Clause := [n 0, p 1, n 4, n 5]
  let c10 : Clause := [p 0, p 1, p 2]
  let c11 : Clause := [p 0, p 1, n 4, n 5]
  let c12 : Clause := [p 1, n 4, n 5]
  let c13 : Clause := [n 4, n 5]
  let c14 : Clause := [n 0, p 3, p 4]
  let c15 : Clause := [n 0, n 1, p 4, n 5]
  let c16 : Clause := [p 0, n 1, n 2]
  let c17 : Clause := [p 2, p 4, n 5]
  let c18 : Clause := [p 0, n 1, p 4, n 5]
  let c19 : Clause := [n 1, p 4, n 5]
  let c20 : Clause := [n 0, p 1, n 2]
  let c21 : Clause := [n 0, p 1, p 4, n 5]
  let c22 : Clause := [p 0, n 3, p 4]
  let c23 : Clause := [p 0, p 1, p 4, n 5]
  let c24 : Clause := [p 1, p 4, n 5]
  let c25 : Clause := [p 4, n 5]
  let c26 : Clause := [n 5]
  let c27 : Clause := [n 1, p 3, p 5]
  let c28 : Clause := [n 0, n 1, n 4, p 5]
  let c29 : Clause := [p 2, n 4, p 5]
  let c30 : Clause := [p 0, n 1, n 4, p 5]
  let c31 : Clause := [n 1, n 4, p 5]
  let c32 : Clause := [n 0, p 1, n 4, p 5]
  let c33 : Clause := [p 1, n 3, p 5]
  let c34 : Clause := [p 0, p 1, n 4, p 5]
  let c35 : Clause := [p 1, n 4, p 5]
  let c36 : Clause := [n 4, p 5]
  let c37 : Clause := [n 2, p 4, p 5]
  let c38 : Clause := [n 0, n 1, p 4, p 5]
  let c39 : Clause := [p 0, n 1, p 4, p 5]
  let c40 : Clause := [n 1, p 4, p 5]
  let c41 : Clause := [n 0, p 1, p 4, p 5]
  let c42 : Clause := [p 0, p 1, p 4, p 5]
  let c43 : Clause := [p 1, p 4, p 5]
  let c44 : Clause := [p 4, p 5]
  let c45 : Clause := [p 5]
  let c46 : Clause := []

  have d0 : SetResolutionDerivation k4OddTseitinCNF c0 :=
    .initial c0 (by decide)
  have d1 : SetResolutionDerivation k4OddTseitinCNF c1 :=
    .initial c1 (by decide)
  have d2 : SetResolutionDerivation k4OddTseitinCNF c2 :=
    .resolve 2 c1 c0 c2
      (by decide) (by decide) (by decide) d1 d0
  have d3 : SetResolutionDerivation k4OddTseitinCNF c3 :=
    .initial c3 (by decide)
  have d4 : SetResolutionDerivation k4OddTseitinCNF c4 :=
    .initial c4 (by decide)
  have d5 : SetResolutionDerivation k4OddTseitinCNF c5 :=
    .resolve 3 c4 c3 c5
      (by decide) (by decide) (by decide) d4 d3
  have d6 : SetResolutionDerivation k4OddTseitinCNF c6 :=
    .resolve 0 c5 c2 c6
      (by decide) (by decide) (by decide) d5 d2
  have d7 : SetResolutionDerivation k4OddTseitinCNF c7 :=
    .initial c7 (by decide)
  have d8 : SetResolutionDerivation k4OddTseitinCNF c8 :=
    .initial c8 (by decide)
  have d9 : SetResolutionDerivation k4OddTseitinCNF c9 :=
    .resolve 3 c8 c7 c9
      (by decide) (by decide) (by decide) d8 d7
  have d10 : SetResolutionDerivation k4OddTseitinCNF c10 :=
    .initial c10 (by decide)
  have d11 : SetResolutionDerivation k4OddTseitinCNF c11 :=
    .resolve 2 c10 c0 c11
      (by decide) (by decide) (by decide) d10 d0
  have d12 : SetResolutionDerivation k4OddTseitinCNF c12 :=
    .resolve 0 c11 c9 c12
      (by decide) (by decide) (by decide) d11 d9
  have d13 : SetResolutionDerivation k4OddTseitinCNF c13 :=
    .resolve 1 c12 c6 c13
      (by decide) (by decide) (by decide) d12 d6
  have d14 : SetResolutionDerivation k4OddTseitinCNF c14 :=
    .initial c14 (by decide)
  have d15 : SetResolutionDerivation k4OddTseitinCNF c15 :=
    .resolve 3 c14 c3 c15
      (by decide) (by decide) (by decide) d14 d3
  have d16 : SetResolutionDerivation k4OddTseitinCNF c16 :=
    .initial c16 (by decide)
  have d17 : SetResolutionDerivation k4OddTseitinCNF c17 :=
    .initial c17 (by decide)
  have d18 : SetResolutionDerivation k4OddTseitinCNF c18 :=
    .resolve 2 c17 c16 c18
      (by decide) (by decide) (by decide) d17 d16
  have d19 : SetResolutionDerivation k4OddTseitinCNF c19 :=
    .resolve 0 c18 c15 c19
      (by decide) (by decide) (by decide) d18 d15
  have d20 : SetResolutionDerivation k4OddTseitinCNF c20 :=
    .initial c20 (by decide)
  have d21 : SetResolutionDerivation k4OddTseitinCNF c21 :=
    .resolve 2 c17 c20 c21
      (by decide) (by decide) (by decide) d17 d20
  have d22 : SetResolutionDerivation k4OddTseitinCNF c22 :=
    .initial c22 (by decide)
  have d23 : SetResolutionDerivation k4OddTseitinCNF c23 :=
    .resolve 3 c8 c22 c23
      (by decide) (by decide) (by decide) d8 d22
  have d24 : SetResolutionDerivation k4OddTseitinCNF c24 :=
    .resolve 0 c23 c21 c24
      (by decide) (by decide) (by decide) d23 d21
  have d25 : SetResolutionDerivation k4OddTseitinCNF c25 :=
    .resolve 1 c24 c19 c25
      (by decide) (by decide) (by decide) d24 d19
  have d26 : SetResolutionDerivation k4OddTseitinCNF c26 :=
    .resolve 4 c25 c13 c26
      (by decide) (by decide) (by decide) d25 d13
  have d27 : SetResolutionDerivation k4OddTseitinCNF c27 :=
    .initial c27 (by decide)
  have d28 : SetResolutionDerivation k4OddTseitinCNF c28 :=
    .resolve 3 c27 c7 c28
      (by decide) (by decide) (by decide) d27 d7
  have d29 : SetResolutionDerivation k4OddTseitinCNF c29 :=
    .initial c29 (by decide)
  have d30 : SetResolutionDerivation k4OddTseitinCNF c30 :=
    .resolve 2 c29 c16 c30
      (by decide) (by decide) (by decide) d29 d16
  have d31 : SetResolutionDerivation k4OddTseitinCNF c31 :=
    .resolve 0 c30 c28 c31
      (by decide) (by decide) (by decide) d30 d28
  have d32 : SetResolutionDerivation k4OddTseitinCNF c32 :=
    .resolve 2 c29 c20 c32
      (by decide) (by decide) (by decide) d29 d20
  have d33 : SetResolutionDerivation k4OddTseitinCNF c33 :=
    .initial c33 (by decide)
  have d34 : SetResolutionDerivation k4OddTseitinCNF c34 :=
    .resolve 3 c4 c33 c34
      (by decide) (by decide) (by decide) d4 d33
  have d35 : SetResolutionDerivation k4OddTseitinCNF c35 :=
    .resolve 0 c34 c32 c35
      (by decide) (by decide) (by decide) d34 d32
  have d36 : SetResolutionDerivation k4OddTseitinCNF c36 :=
    .resolve 1 c35 c31 c36
      (by decide) (by decide) (by decide) d35 d31
  have d37 : SetResolutionDerivation k4OddTseitinCNF c37 :=
    .initial c37 (by decide)
  have d38 : SetResolutionDerivation k4OddTseitinCNF c38 :=
    .resolve 2 c1 c37 c38
      (by decide) (by decide) (by decide) d1 d37
  have d39 : SetResolutionDerivation k4OddTseitinCNF c39 :=
    .resolve 3 c27 c22 c39
      (by decide) (by decide) (by decide) d27 d22
  have d40 : SetResolutionDerivation k4OddTseitinCNF c40 :=
    .resolve 0 c39 c38 c40
      (by decide) (by decide) (by decide) d39 d38
  have d41 : SetResolutionDerivation k4OddTseitinCNF c41 :=
    .resolve 3 c14 c33 c41
      (by decide) (by decide) (by decide) d14 d33
  have d42 : SetResolutionDerivation k4OddTseitinCNF c42 :=
    .resolve 2 c10 c37 c42
      (by decide) (by decide) (by decide) d10 d37
  have d43 : SetResolutionDerivation k4OddTseitinCNF c43 :=
    .resolve 0 c42 c41 c43
      (by decide) (by decide) (by decide) d42 d41
  have d44 : SetResolutionDerivation k4OddTseitinCNF c44 :=
    .resolve 1 c43 c40 c44
      (by decide) (by decide) (by decide) d43 d40
  have d45 : SetResolutionDerivation k4OddTseitinCNF c45 :=
    .resolve 4 c44 c36 c45
      (by decide) (by decide) (by decide) d44 d36
  have d46 : SetResolutionDerivation k4OddTseitinCNF c46 :=
    .resolve 5 c45 c26 c46
      (by decide) (by decide) (by decide) d45 d26
  exact d46

theorem k4_set_resolution_certificate_unsat :
    ¬ ∃ assignment, evalCNF assignment k4OddTseitinCNF = true :=
  set_resolution_refutation_unsat k4OddTseitinCNF
    k4_set_resolution_certificate

end AlexandriaComplexity
